name: smart_farm
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  font_awesome_flutter: ^10.5.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  firebase_storage: ^11.2.8
  webview_flutter: ^2.0.13 
  get: ^4.6.6
  flutter_local_notifications: ^16.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
      - images/KU.png
      - images/พื้นหลัง.jpg
      - images/พื้นหลัง1.jpg
      - images/ผัก.jpg
      - images/ผัก2.jpg
      - images/pro.jpg
      - images/ชื้นดิน.png
      - images/ชื้นอากาศ.jpg
      - images/อุณหภูมิ.png
      - images/logo app.jpg